#+BEGIN_COMMENT
.. title: GlPortal is a free 3d action adventure
.. slug: index
.. date: 2014-11-22 12:46:06 UTC+01:00
.. tags: 
.. link: 
.. description: 
.. type: text
.. hidetitle: True
.. slitslider: True
#+END_COMMENT

#+INCLUDE: "slider.inc.org" :minlevel 1
#+MACRO: begin_panel #+HTML: <div class="panel panel-default"><div class="panel-body">
#+MACRO: end_panel #+HTML: </div></div>
#+MACRO: col #+HTML: <div class="col-md-$1">
#+MACRO: anchor #+HTML: <span id="anchor-$1"/>
#+MACRO: primary_button #+HTML: <a class="btn btn-normal btn-primary" target="_blank" href="$2">$1</a>
#+MACRO: jumbotron #+HTML: <div class="jumbotron">
#+MACRO: end #+HTML: </div>

#+BEGIN_HTML
<h1>GlPortal is a free 3d action adventure</h1>
<div class="panel panel-default">
  <div class="panel-body">
    <p>
#+END_HTML
      Press download to get a build from indiedb or use the source button to get to our repository on github.
      If you encounter a bug, please report it.
#+BEGIN_HTML
    </p>

    <div class="btn-group" role="group">
      <a class="btn btn-normal btn-success btn-lg" target="_blank" href="http://www.indiedb.com/games/glportal/downloads"><i class="glyphicon glyphicon-download"></i> Download</a>
      <a class="btn btn-normal btn-primary  btn-lg" target="_blank" href="https://github.com/GlPortal/glPortal"><i class="glyphicon glyphicon-folder-close"></i> Source Code</a>
      <a class="btn btn-normal btn-lg" href="#help"><i class="glyphicon glyphicon-heart"></i> Help</a>
      <a class="btn btn-normal btn-danger btn-lg" target="_blank" href="http://bugs.glportal.de"><i class="glyphicon glyphicon-bullhorn"></i> Report a Bug</a>
    </div>
  </div>
</div>


<div class="row">
#+END_HTML

{{{col(8)}}}
{{{jumbotron()}}}

      GlPortal is a free as in freedom game and game engine for GNU/Linux, Windows and Mac OS X. 

      The player has to solve puzzles with the help of teleportation and physics manipulation.

{{{end()}}}
{{{end()}}}


{{{col(4)}}}
* Overview
- Support Us
- Take a look at the game

* Features
- Free and open game and engine
- Enthusiastic community
- Active Developers

{{{end()}}}
{{{end()}}}

* Take A Look
#+BEGIN_HTML
<a class="btn btn-normal btn-primary" href="/galleries/screenshots/">Screenshots</a>
<a class="btn btn-normal btn-primary" href="/galleries/art/">Game Art</a>
<a class="btn btn-normal btn-primary" href="https://www.youtube.com/results?search_query=glportal">Videos@Youtube</a>
#+END_HTML
The current release is v0.0.7.1 frogger
* Getting Started
{{{anchor(start)}}}

* Support Us
** Vote For Us
You can support us by voting for us on:

{{{anchor(help)}}}
{{{primary_button(Indiedb, http://www.indiedb.com/games/glportal)}}}
{{{primary_button(LGDB, http://www.lgdb.org/game/glportal-free)}}}

** Create Screenshots And Videos
* Join the Team
#+INCLUDE: "join.inc.org" :minlevel 1
#+BEGIN_HTML 
<!-- Button trigger modal -->
<button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">
  Launch demo modal
</button>

<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h2 class="modal-title" id="myModalLabel">Modal title</h4>
      </div>
      <div class="modal-body">
#+END_HTML 
Dies ist ein Test
#+BEGIN_HTML 
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>
#+END_HTML


Stuff
Stuff

Stuff
StuffStuff
Stuff

Stuff
StuffStuff
Stuff

Stuff
StuffStuff
Stuff

Stuff
StuffStuff
Stuff

Stuff
StuffStuff
Stuff

#+BEGIN_HTML 


 
<div data-sr="wait 0.5s and then ease-in-out 200px"> 
  <p>GlPortal rocks!</p>
  <p>Stuff</p>
  <p>StuffStuff</p>
  <p>Stuff</p>

  <p>Stuff</p>
  <p>StuffStuff</p>
  <p>Stuff</p>

  <p>Stuff</p>
</div>

#+END_HTML

Stuff
StuffStuff
Stuff

Stuff
StuffStuff
Stuff

Stuff
Stuff
